require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '14.0' # 최소 iOS 버전
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyNewProject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true # Hermes JS 엔진 활성화 여부
  )

  target 'MyNewProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # React Native 설치 후 필요한 추가 설정
  post_install do |installer|
    # React Native 설치 후 설정
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false, # Mac Catalyst 비활성화
    )
    # Xcode 설정 업데이트 및 Codegen 관련 처리
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end

      # Codegen 관련 경고 해결
      if target.name == 'React-Codegen'
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
      end
    end
  end
end